apiVersion: v1
kind: Service
metadata:
  name: hotels-microservice-service
spec:
  selector:
    app: hotels-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
