# Generated by Django 4.2.1 on 2024-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('hotelname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('first_image', models.BinaryField()),
                ('second_image', models.BinaryField()),
                ('third_image', models.BinaryField()),
                ('fourth_image', models.BinaryField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
