# Generated by Django 4.2.1 on 2024-05-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotels_first_image_alter_hotels_fourth_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='first_image',
        ),
    ]
