# Generated by Django 4.2.1 on 2024-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotels_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
